name: Build pdf

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latex packages
        run: sudo apt-get install texlive texlive-latex-utils texlive-fonts-extra -y

      - name: Build
        run: pdflatex -output-directory=./build main.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: ./build/main.pdf
